USE [master];
GO

/* =========================================================
   SCRIPT COMPLETO - 2 BASES DE DATOS
   PROPUESTA:
   1) BD_CATALOGO   -> maestros, usuarios y productos
   2) BD_TRANSACCIONES -> compras, ventas y kardex

   NOTA IMPORTANTE:
   SQL Server NO permite foreign keys reales entre bases de datos distintas.
   Por eso:
   - USU_ID en BD_TRANSACCIONES queda como referencia lógica
   - PROD_ID en BD_TRANSACCIONES queda como referencia lógica
   - CREATED_BY / UPDATED_BY / DELETED_BY en BD_TRANSACCIONES quedan como referencia lógica
   La validación se hace desde los microservicios.
   ========================================================= */

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'BD_CATALOGO')
BEGIN
    CREATE DATABASE [BD_CATALOGO]
    ON PRIMARY ( NAME = N'BD_CATALOGO', FILENAME = N'/var/opt/mssql/data/BD_CATALOGO.mdf' )
    LOG ON ( NAME = N'BD_CATALOGO_log', FILENAME = N'/var/opt/mssql/data/BD_CATALOGO_log.ldf' )
END
GO

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'BD_TRANSACCIONES')
BEGIN
    CREATE DATABASE [BD_TRANSACCIONES]
    ON PRIMARY ( NAME = N'BD_TRANSACCIONES', FILENAME = N'/var/opt/mssql/data/BD_TRANSACCIONES.mdf' )
    LOG ON ( NAME = N'BD_TRANSACCIONES_log', FILENAME = N'/var/opt/mssql/data/BD_TRANSACCIONES_log.ldf' )
END
GO

/* =========================================================
   BASE 1: BD_CATALOGO
   - USUARIO
   - CONFIGURACION
   - MARCA
   - CATEGORIA (antes TIPO)
   - PRODUCTO
   - IMAGEN
   ========================================================= */
USE [BD_CATALOGO];
GO

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

/* =========================================
   1) USUARIO
   - Se elimina ROL y USUARIO_ROL
   - El rol queda integrado en USUARIO
   ========================================= */
CREATE TABLE [dbo].[USUARIO](
    [USU_ID]        INT IDENTITY(1,1) NOT NULL,
    [USU_CEDULA]    VARCHAR(13) NOT NULL,
    [USU_NOMBRE]    VARCHAR(50) NOT NULL,
    [USU_APELLIDO]  VARCHAR(50) NOT NULL,
    [USU_ROL]       VARCHAR(30) NOT NULL CONSTRAINT [DF_USU_ROL] DEFAULT ('ADMIN'),
    [USU_ESTADO]    BIT NOT NULL CONSTRAINT [DF_USU_ESTADO] DEFAULT ((1)),
    [USU_PASSWORD]  VARCHAR(255) NULL,

    [CREATED_AT] DATETIME2(0) NOT NULL CONSTRAINT [DF_USU_CREATED_AT] DEFAULT (sysdatetime()),
    [UPDATED_AT] DATETIME2(0) NULL,
    [DELETED_AT] DATETIME2(0) NULL,
    [CREATED_BY] INT NULL,
    [UPDATED_BY] INT NULL,
    [DELETED_BY] INT NULL,

    CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED ([USU_ID] ASC)
) ON [PRIMARY];
GO

CREATE UNIQUE NONCLUSTERED INDEX [UQ_USU_CEDULA]
ON [dbo].[USUARIO]([USU_CEDULA] ASC)
WHERE [DELETED_AT] IS NULL;
GO

ALTER TABLE [dbo].[USUARIO] WITH CHECK
ADD CONSTRAINT [CK_USU_ROL]
CHECK ([USU_ROL] IN ('ADMIN','OPERADOR','VENDEDOR'));
GO

/* =========================================
   2) CONFIGURACION
   ========================================= */
CREATE TABLE [dbo].[CONFIGURACION](
    [CONF_ID]           INT IDENTITY(1,1) NOT NULL,
    [IVA_PORCENTAJE]    DECIMAL(5,2) NOT NULL CONSTRAINT [DF_CONF_IVA] DEFAULT (15.00),
    [ESTABLECIMIENTO]   VARCHAR(3) NOT NULL CONSTRAINT [DF_CONF_EST] DEFAULT ('001'),
    [PUNTO_EMISION]     VARCHAR(3) NOT NULL CONSTRAINT [DF_CONF_PTO] DEFAULT ('001'),
    [ULTIMO_SECUENCIAL] INT NOT NULL CONSTRAINT [DF_CONF_SEC] DEFAULT ((0)),

    [CREATED_AT] DATETIME2(0) NOT NULL CONSTRAINT [DF_CONF_CREATED_AT] DEFAULT (sysdatetime()),
    [UPDATED_AT] DATETIME2(0) NULL,
    [DELETED_AT] DATETIME2(0) NULL,
    [CREATED_BY] INT NULL,
    [UPDATED_BY] INT NULL,
    [DELETED_BY] INT NULL,

    CONSTRAINT [PK_CONFIGURACION] PRIMARY KEY CLUSTERED ([CONF_ID] ASC)
) ON [PRIMARY];
GO

ALTER TABLE [dbo].[CONFIGURACION] WITH CHECK
ADD CONSTRAINT [CK_CONF_IVA] CHECK ([IVA_PORCENTAJE] >= (0) AND [IVA_PORCENTAJE] <= (100));
GO

ALTER TABLE [dbo].[CONFIGURACION] WITH CHECK
ADD CONSTRAINT [CK_CONF_SECU] CHECK ([ULTIMO_SECUENCIAL] >= (0));
GO

/* =========================================
   3) MARCA
   ========================================= */
CREATE TABLE [dbo].[MARCA](
    [MARCA_ID]     INT IDENTITY(1,1) NOT NULL,
    [MARCA_NOMBRE] VARCHAR(50) NOT NULL,

    [CREATED_AT] DATETIME2(0) NOT NULL CONSTRAINT [DF_MARCA_CREATED_AT] DEFAULT (sysdatetime()),
    [UPDATED_AT] DATETIME2(0) NULL,
    [DELETED_AT] DATETIME2(0) NULL,
    [CREATED_BY] INT NULL,
    [UPDATED_BY] INT NULL,
    [DELETED_BY] INT NULL,

    CONSTRAINT [PK_MARCA] PRIMARY KEY CLUSTERED ([MARCA_ID] ASC)
) ON [PRIMARY];
GO

CREATE UNIQUE NONCLUSTERED INDEX [UQ_MARCA_NOMBRE]
ON [dbo].[MARCA]([MARCA_NOMBRE] ASC)
WHERE [DELETED_AT] IS NULL;
GO

/* =========================================
   4) CATEGORIA (antes TIPO)
   ========================================= */
CREATE TABLE [dbo].[CATEGORIA](
    [CAT_ID]         INT IDENTITY(1,1) NOT NULL,
    [CAT_NOMBRE]     VARCHAR(50) NOT NULL,

    [CREATED_AT] DATETIME2(0) NOT NULL CONSTRAINT [DF_CAT_CREATED_AT] DEFAULT (sysdatetime()),
    [UPDATED_AT] DATETIME2(0) NULL,
    [DELETED_AT] DATETIME2(0) NULL,
    [CREATED_BY] INT NULL,
    [UPDATED_BY] INT NULL,
    [DELETED_BY] INT NULL,

    CONSTRAINT [PK_CATEGORIA] PRIMARY KEY CLUSTERED ([CAT_ID] ASC)
) ON [PRIMARY];
GO

CREATE UNIQUE NONCLUSTERED INDEX [UQ_CAT_NOMBRE]
ON [dbo].[CATEGORIA]([CAT_NOMBRE] ASC)
WHERE [DELETED_AT] IS NULL;
GO

/* =========================================
   5) PRODUCTO
   - se cambia TIPO_ID por CAT_ID
   - se agrega descripcion
   - se agrega cantidad / stock
   ========================================= */
CREATE TABLE [dbo].[PRODUCTO](
    [PROD_ID]               INT IDENTITY(1,1) NOT NULL,
    [PROD_NOMBRE]           VARCHAR(100) NOT NULL,
    [PROD_DESCRIPCION]      VARCHAR(500) NULL,
    [CAT_ID]                INT NOT NULL,
    [MARCA_ID]              INT NOT NULL,
    [PROD_PRECIOVEN]        DECIMAL(10,2) NOT NULL,
    [PROD_PRECIOCOM]        DECIMAL(10,2) NOT NULL,
    [PROD_CANTIDAD]         INT NOT NULL CONSTRAINT [DF_PROD_CANTIDAD] DEFAULT ((0)),
    [PROD_ESTADO]           BIT NOT NULL CONSTRAINT [DF_PROD_ESTADO] DEFAULT ((1)),

    [CREATED_AT] DATETIME2(0) NOT NULL CONSTRAINT [DF_PROD_CREATED_AT] DEFAULT (sysdatetime()),
    [UPDATED_AT] DATETIME2(0) NULL,
    [DELETED_AT] DATETIME2(0) NULL,
    [CREATED_BY] INT NULL,
    [UPDATED_BY] INT NULL,
    [DELETED_BY] INT NULL,

    CONSTRAINT [PK_PRODUCTO] PRIMARY KEY CLUSTERED ([PROD_ID] ASC)
) ON [PRIMARY];
GO

CREATE NONCLUSTERED INDEX [IX_PROD_CAT]
ON [dbo].[PRODUCTO]([CAT_ID] ASC);
GO

CREATE NONCLUSTERED INDEX [IX_PROD_MARCA]
ON [dbo].[PRODUCTO]([MARCA_ID] ASC);
GO

ALTER TABLE [dbo].[PRODUCTO] WITH CHECK
ADD CONSTRAINT [CK_PROD_PRECIOCOM] CHECK ([PROD_PRECIOCOM] >= (0));
GO

ALTER TABLE [dbo].[PRODUCTO] WITH CHECK
ADD CONSTRAINT [CK_PROD_PRECIOVEN] CHECK ([PROD_PRECIOVEN] >= (0));
GO

ALTER TABLE [dbo].[PRODUCTO] WITH CHECK
ADD CONSTRAINT [CK_PROD_CANTIDAD] CHECK ([PROD_CANTIDAD] >= (0));
GO

/* =========================================
   6) IMAGEN
   - una imagen pertenece a un solo producto
   - un producto puede tener muchas imagenes
   ========================================= */
CREATE TABLE [dbo].[IMAGEN](
    [IMG_ID]         INT IDENTITY(1,1) NOT NULL,
    [PROD_ID]        INT NOT NULL,
    [IMG_NOMBRE]     VARCHAR(150) NULL,
    [IMG_URL]        VARCHAR(500) NOT NULL,
    [IMG_DESCRIPCION]   VARCHAR(250) NULL,
    [ES_PRINCIPAL]      BIT NOT NULL CONSTRAINT [DF_IMG_PRINCIPAL] DEFAULT ((0)),
    [ORDEN]          INT NOT NULL CONSTRAINT [DF_IMG_ORDEN] DEFAULT ((1)),
    [IMG_ESTADO]     BIT NOT NULL CONSTRAINT [DF_IMG_ESTADO] DEFAULT ((1)),

    [CREATED_AT] DATETIME2(0) NOT NULL CONSTRAINT [DF_IMG_CREATED_AT] DEFAULT (sysdatetime()),
    [UPDATED_AT] DATETIME2(0) NULL,
    [DELETED_AT] DATETIME2(0) NULL,
    [CREATED_BY] INT NULL,
    [UPDATED_BY] INT NULL,
    [DELETED_BY] INT NULL,

    CONSTRAINT [PK_IMAGEN] PRIMARY KEY CLUSTERED ([IMG_ID] ASC)
) ON [PRIMARY];
GO

CREATE NONCLUSTERED INDEX [IX_IMG_PROD]
ON [dbo].[IMAGEN]([PROD_ID] ASC);
GO

ALTER TABLE [dbo].[IMAGEN] WITH CHECK
ADD CONSTRAINT [CK_IMG_ORDEN] CHECK ([ORDEN] > (0));
GO

/* =========================================
   7) Foreign Keys negocio BD_CATALOGO
   ========================================= */
ALTER TABLE [dbo].[PRODUCTO] WITH CHECK
ADD CONSTRAINT [FK_PRODUCTO_CATEGORIA]
FOREIGN KEY ([CAT_ID]) REFERENCES [dbo].[CATEGORIA]([CAT_ID]);
GO

ALTER TABLE [dbo].[PRODUCTO] WITH CHECK
ADD CONSTRAINT [FK_PRODUCTO_MARCA]
FOREIGN KEY ([MARCA_ID]) REFERENCES [dbo].[MARCA]([MARCA_ID]);
GO

ALTER TABLE [dbo].[IMAGEN] WITH CHECK
ADD CONSTRAINT [FK_IMAGEN_PRODUCTO]
FOREIGN KEY ([PROD_ID]) REFERENCES [dbo].[PRODUCTO]([PROD_ID]);
GO

/* =========================================
   8) Foreign Keys auditoría BD_CATALOGO
   ========================================= */
ALTER TABLE dbo.USUARIO         WITH CHECK ADD CONSTRAINT [FK_USU_CREATED_BY]  FOREIGN KEY ([CREATED_BY]) REFERENCES dbo.USUARIO([USU_ID]);
ALTER TABLE dbo.USUARIO         WITH CHECK ADD CONSTRAINT [FK_USU_UPDATED_BY]  FOREIGN KEY ([UPDATED_BY]) REFERENCES dbo.USUARIO([USU_ID]);
ALTER TABLE dbo.USUARIO         WITH CHECK ADD CONSTRAINT [FK_USU_DELETED_BY]  FOREIGN KEY ([DELETED_BY]) REFERENCES dbo.USUARIO([USU_ID]);
GO

ALTER TABLE dbo.CONFIGURACION   WITH CHECK ADD CONSTRAINT [FK_CONF_CREATED_BY] FOREIGN KEY ([CREATED_BY]) REFERENCES dbo.USUARIO([USU_ID]);
ALTER TABLE dbo.CONFIGURACION   WITH CHECK ADD CONSTRAINT [FK_CONF_UPDATED_BY] FOREIGN KEY ([UPDATED_BY]) REFERENCES dbo.USUARIO([USU_ID]);
ALTER TABLE dbo.CONFIGURACION   WITH CHECK ADD CONSTRAINT [FK_CONF_DELETED_BY] FOREIGN KEY ([DELETED_BY]) REFERENCES dbo.USUARIO([USU_ID]);
GO

ALTER TABLE dbo.MARCA           WITH CHECK ADD CONSTRAINT [FK_MARCA_CREATED_BY] FOREIGN KEY ([CREATED_BY]) REFERENCES dbo.USUARIO([USU_ID]);
ALTER TABLE dbo.MARCA           WITH CHECK ADD CONSTRAINT [FK_MARCA_UPDATED_BY] FOREIGN KEY ([UPDATED_BY]) REFERENCES dbo.USUARIO([USU_ID]);
ALTER TABLE dbo.MARCA           WITH CHECK ADD CONSTRAINT [FK_MARCA_DELETED_BY] FOREIGN KEY ([DELETED_BY]) REFERENCES dbo.USUARIO([USU_ID]);
GO

ALTER TABLE dbo.CATEGORIA       WITH CHECK ADD CONSTRAINT [FK_CAT_CREATED_BY] FOREIGN KEY ([CREATED_BY]) REFERENCES dbo.USUARIO([USU_ID]);
ALTER TABLE dbo.CATEGORIA       WITH CHECK ADD CONSTRAINT [FK_CAT_UPDATED_BY] FOREIGN KEY ([UPDATED_BY]) REFERENCES dbo.USUARIO([USU_ID]);
ALTER TABLE dbo.CATEGORIA       WITH CHECK ADD CONSTRAINT [FK_CAT_DELETED_BY] FOREIGN KEY ([DELETED_BY]) REFERENCES dbo.USUARIO([USU_ID]);
GO

ALTER TABLE dbo.PRODUCTO        WITH CHECK ADD CONSTRAINT [FK_PROD_CREATED_BY] FOREIGN KEY ([CREATED_BY]) REFERENCES dbo.USUARIO([USU_ID]);
ALTER TABLE dbo.PRODUCTO        WITH CHECK ADD CONSTRAINT [FK_PROD_UPDATED_BY] FOREIGN KEY ([UPDATED_BY]) REFERENCES dbo.USUARIO([USU_ID]);
ALTER TABLE dbo.PRODUCTO        WITH CHECK ADD CONSTRAINT [FK_PROD_DELETED_BY] FOREIGN KEY ([DELETED_BY]) REFERENCES dbo.USUARIO([USU_ID]);
GO

ALTER TABLE dbo.IMAGEN          WITH CHECK ADD CONSTRAINT [FK_IMG_CREATED_BY] FOREIGN KEY ([CREATED_BY]) REFERENCES dbo.USUARIO([USU_ID]);
ALTER TABLE dbo.IMAGEN          WITH CHECK ADD CONSTRAINT [FK_IMG_UPDATED_BY] FOREIGN KEY ([UPDATED_BY]) REFERENCES dbo.USUARIO([USU_ID]);
ALTER TABLE dbo.IMAGEN          WITH CHECK ADD CONSTRAINT [FK_IMG_DELETED_BY] FOREIGN KEY ([DELETED_BY]) REFERENCES dbo.USUARIO([USU_ID]);
GO

GO

/* =========================================================
   BASE 2: BD_TRANSACCIONES
   - CLIENTE
   - PROVEEDOR
   - TIPO_PAGO
   - FACTURA
   - PRODUCTO_FACTURA
   - KARDEX
   - COMPRA
   - PRODUCTO_COMPRA
   ========================================================= */
USE [BD_TRANSACCIONES];
GO

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

/* =========================================
   1) CLIENTE
   ========================================= */
CREATE TABLE [dbo].[CLIENTE](
    [CLI_ID]         INT IDENTITY(1,1) NOT NULL,
    [CLI_CEDULA]     VARCHAR(13) NULL,
    [CLI_NOMBRE]     VARCHAR(50) NOT NULL,
    [CLI_APELLIDO]   VARCHAR(50) NOT NULL,
    [CLI_DIRECCION]  VARCHAR(100) NULL,
    [CLI_CORREO]     VARCHAR(250) NULL,
    [CLI_TELEFONO]   VARCHAR(10) NULL,

    [CREATED_AT] DATETIME2(0) NOT NULL CONSTRAINT [DF_CLI_CREATED_AT] DEFAULT (sysdatetime()),
    [UPDATED_AT] DATETIME2(0) NULL,
    [DELETED_AT] DATETIME2(0) NULL,
    [CREATED_BY] INT NULL,
    [UPDATED_BY] INT NULL,
    [DELETED_BY] INT NULL,

    CONSTRAINT [PK_CLIENTE] PRIMARY KEY CLUSTERED ([CLI_ID] ASC)
) ON [PRIMARY];
GO

CREATE UNIQUE NONCLUSTERED INDEX [UQ_CLI_CEDULA]
ON [dbo].[CLIENTE]([CLI_CEDULA] ASC)
WHERE [CLI_CEDULA] IS NOT NULL AND [DELETED_AT] IS NULL;
GO

/* =========================================
   2) PROVEEDOR
   ========================================= */
CREATE TABLE [dbo].[PROVEEDOR](
    [PROV_ID]         INT IDENTITY(1,1) NOT NULL,
    [PROV_NOMBRE]     VARCHAR(150) NOT NULL,
    [PROV_RUC]        VARCHAR(13) NULL,
    [PROV_TELEFONO]   VARCHAR(15) NULL,
    [PROV_DIRECCION]  VARCHAR(250) NULL,
    [PROV_CORREO]     VARCHAR(250) NULL,

    [CREATED_AT] DATETIME2(0) NOT NULL CONSTRAINT [DF_PROV_CREATED_AT] DEFAULT (sysdatetime()),
    [UPDATED_AT] DATETIME2(0) NULL,
    [DELETED_AT] DATETIME2(0) NULL,
    [CREATED_BY] INT NULL,
    [UPDATED_BY] INT NULL,
    [DELETED_BY] INT NULL,

    CONSTRAINT [PK_PROVEEDOR] PRIMARY KEY CLUSTERED ([PROV_ID] ASC)
) ON [PRIMARY];
GO

CREATE UNIQUE NONCLUSTERED INDEX [UQ_PROV_RUC]
ON [dbo].[PROVEEDOR]([PROV_RUC] ASC)
WHERE [PROV_RUC] IS NOT NULL AND [DELETED_AT] IS NULL;
GO

/* =========================================
   3) TIPO_PAGO
   ========================================= */
CREATE TABLE [dbo].[TIPO_PAGO](
    [TPA_ID]       INT IDENTITY(1,1) NOT NULL,
    [TPA_NOMBRE]   VARCHAR(30) NOT NULL,

    [CREATED_AT] DATETIME2(0) NOT NULL CONSTRAINT [DF_TPA_CREATED_AT] DEFAULT (sysdatetime()),
    [UPDATED_AT] DATETIME2(0) NULL,
    [DELETED_AT] DATETIME2(0) NULL,
    [CREATED_BY] INT NULL,
    [UPDATED_BY] INT NULL,
    [DELETED_BY] INT NULL,

    CONSTRAINT [PK_TIPO_PAGO] PRIMARY KEY CLUSTERED ([TPA_ID] ASC)
) ON [PRIMARY];
GO

CREATE UNIQUE NONCLUSTERED INDEX [UQ_TPA_NOMBRE]
ON [dbo].[TIPO_PAGO]([TPA_NOMBRE] ASC)
WHERE [DELETED_AT] IS NULL;
GO

/* =========================================
   4) FACTURA
   NOTA:
   - USU_ID es referencia lógica al usuario de BD_CATALOGO
   ========================================= */
CREATE TABLE [dbo].[FACTURA](
    [FAC_ID]            INT IDENTITY(1,1) NOT NULL,
    [CLI_ID]            INT NOT NULL,
    [USU_ID]            INT NULL,
    [TPA_ID]            INT NOT NULL,
    [FAC_FECHA]         DATE NOT NULL,
    [FAC_NUMERO_SERIE]  VARCHAR(20) NULL,
    [FAC_SUBTOTAL]      DECIMAL(10,2) NOT NULL CONSTRAINT [DF_FAC_SUBTOTAL] DEFAULT ((0)),
    [FAC_IVA_VALOR]     DECIMAL(10,2) NOT NULL CONSTRAINT [DF_FAC_IVA] DEFAULT ((0)),
    [FAC_TOTAL]         DECIMAL(10,2) NOT NULL CONSTRAINT [DF_FAC_TOTAL] DEFAULT ((0)),
    [FAC_ESTADO]        BIT NULL CONSTRAINT [DF_FAC_ESTADO] DEFAULT ((1)),

    [CREATED_AT] DATETIME2(0) NOT NULL CONSTRAINT [DF_FAC_CREATED_AT] DEFAULT (sysdatetime()),
    [UPDATED_AT] DATETIME2(0) NULL,
    [DELETED_AT] DATETIME2(0) NULL,
    [CREATED_BY] INT NULL,
    [UPDATED_BY] INT NULL,
    [DELETED_BY] INT NULL,

    CONSTRAINT [PK_FACTURA] PRIMARY KEY CLUSTERED ([FAC_ID] ASC)
) ON [PRIMARY];
GO

CREATE UNIQUE NONCLUSTERED INDEX [UQ_FAC_NUMERO_SERIE]
ON [dbo].[FACTURA]([FAC_NUMERO_SERIE] ASC)
WHERE ([FAC_NUMERO_SERIE] IS NOT NULL);
GO

CREATE NONCLUSTERED INDEX [IX_FAC_CLI_FECHA]
ON [dbo].[FACTURA]([CLI_ID] ASC, [FAC_FECHA] ASC);
GO

CREATE NONCLUSTERED INDEX [IX_FAC_USU_FECHA]
ON [dbo].[FACTURA]([USU_ID] ASC, [FAC_FECHA] ASC);
GO

CREATE NONCLUSTERED INDEX [IX_FAC_TPA_FECHA]
ON [dbo].[FACTURA]([TPA_ID] ASC, [FAC_FECHA] ASC);
GO

/* =========================================
   5) PRODUCTO_FACTURA
   NOTA:
   - PROD_ID es referencia lógica al producto de BD_CATALOGO
   ========================================= */
CREATE TABLE [dbo].[PRODUCTO_FACTURA](
    [FAC_ID]          INT NOT NULL,
    [PROD_ID]         INT NOT NULL,
    [FP_CANTIDAD]     INT NOT NULL,
    [FP_PRECIO]       DECIMAL(10,2) NOT NULL,

    CONSTRAINT [PK_PRODUCTO_FACTURA] PRIMARY KEY CLUSTERED ([FAC_ID] ASC, [PROD_ID] ASC)
) ON [PRIMARY];
GO

CREATE NONCLUSTERED INDEX [IX_FP_PROD]
ON [dbo].[PRODUCTO_FACTURA]([PROD_ID] ASC);
GO

ALTER TABLE [dbo].[PRODUCTO_FACTURA] WITH CHECK
ADD CONSTRAINT [CK_FP_CANT] CHECK ([FP_CANTIDAD] > (0));
GO

ALTER TABLE [dbo].[PRODUCTO_FACTURA] WITH CHECK
ADD CONSTRAINT [CK_FP_PREC] CHECK ([FP_PRECIO] >= (0));
GO

/* =========================================
   6) KARDEX
   NOTA:
   - se elimina LOTE
   - PROD_ID y USU_ID quedan como referencia lógica
   ========================================= */
CREATE TABLE [dbo].[KARDEX](
    [KDX_ID]           INT IDENTITY(1,1) NOT NULL,
    [PROD_ID]          INT NOT NULL,
    [USU_ID]           INT NOT NULL,
    [KDX_FECHA]        DATETIME2(0) NOT NULL CONSTRAINT [DF_KDX_FECHA] DEFAULT (sysdatetime()),
    [KDX_TIPO]         VARCHAR(20) NOT NULL,
    [KDX_MOTIVO]       VARCHAR(30) NULL,
    [KDX_DOC_REFER]    VARCHAR(50) NULL,
    [KDX_CANTIDAD]     INT NOT NULL,
    [KDX_SALDO_ANT]    INT NULL,
    [KDX_SALDO_FINAL]  INT NULL,
    [KDX_COSTO_UNIT]   DECIMAL(10,2) NULL,
    [KDX_PRECIO_UNIT]  DECIMAL(10,2) NULL,

    CONSTRAINT [PK_KARDEX] PRIMARY KEY CLUSTERED ([KDX_ID] ASC)
) ON [PRIMARY];
GO

CREATE NONCLUSTERED INDEX [IX_KDX_PROD_FECHA]
ON [dbo].[KARDEX]([PROD_ID] ASC, [KDX_FECHA] ASC);
GO

CREATE NONCLUSTERED INDEX [IX_KDX_USU_FECHA]
ON [dbo].[KARDEX]([USU_ID] ASC, [KDX_FECHA] ASC);
GO

ALTER TABLE [dbo].[KARDEX] WITH CHECK
ADD CONSTRAINT [CK_KDX_TIPO] CHECK ([KDX_TIPO] IN ('Entrada','Salida','Ajuste'));
GO

ALTER TABLE [dbo].[KARDEX] WITH CHECK
ADD CONSTRAINT [CK_KDX_CANT] CHECK ([KDX_CANTIDAD] > (0));
GO

ALTER TABLE [dbo].[KARDEX] WITH CHECK
ADD CONSTRAINT [CK_KDX_COSTO] CHECK ([KDX_COSTO_UNIT] IS NULL OR [KDX_COSTO_UNIT] >= (0));
GO

ALTER TABLE [dbo].[KARDEX] WITH CHECK
ADD CONSTRAINT [CK_KDX_PRECIO] CHECK ([KDX_PRECIO_UNIT] IS NULL OR [KDX_PRECIO_UNIT] >= (0));
GO

ALTER TABLE [dbo].[KARDEX] WITH CHECK
ADD CONSTRAINT [CK_KDX_SALDOS]
CHECK (
    ([KDX_SALDO_ANT] IS NULL AND [KDX_SALDO_FINAL] IS NULL)
 OR ([KDX_SALDO_ANT] IS NOT NULL AND [KDX_SALDO_FINAL] IS NOT NULL)
);
GO

/* =========================================
   7) COMPRA
   NOTA:
   - USU_ID es referencia lógica al usuario de BD_CATALOGO
   ========================================= */
CREATE TABLE [dbo].[COMPRA](
    [COMPRA_ID]      INT IDENTITY(1,1) NOT NULL,
    [PROV_ID]        INT NOT NULL,
    [USU_ID]         INT NOT NULL,
    [COMPRA_FECHA]   DATE NOT NULL,

    [CREATED_AT] DATETIME2(0) NOT NULL CONSTRAINT [DF_COMP_CREATED_AT] DEFAULT (sysdatetime()),
    [UPDATED_AT] DATETIME2(0) NULL,
    [DELETED_AT] DATETIME2(0) NULL,
    [CREATED_BY] INT NULL,
    [UPDATED_BY] INT NULL,
    [DELETED_BY] INT NULL,

    CONSTRAINT [PK_COMPRA] PRIMARY KEY CLUSTERED ([COMPRA_ID] ASC)
) ON [PRIMARY];
GO

CREATE NONCLUSTERED INDEX [IX_COMPRA_PROV_FECHA]
ON [dbo].[COMPRA]([PROV_ID] ASC, [COMPRA_FECHA] ASC);
GO

/* =========================================
   8) PRODUCTO_COMPRA
   NOTA:
   - PROD_ID es referencia lógica al producto de BD_CATALOGO
   ========================================= */
CREATE TABLE [dbo].[PRODUCTO_COMPRA](
    [COMPRA_ID]        INT NOT NULL,
    [PROD_ID]          INT NOT NULL,
    [PRDCOM_CANTIDAD]  INT NOT NULL,
    [PRDCOM_PRECIO]    DECIMAL(10,2) NOT NULL,

    [CREATED_AT] DATETIME2(0) NOT NULL CONSTRAINT [DF_PRDCOM_CREATED_AT] DEFAULT (sysdatetime()),
    [UPDATED_AT] DATETIME2(0) NULL,
    [DELETED_AT] DATETIME2(0) NULL,
    [CREATED_BY] INT NULL,
    [UPDATED_BY] INT NULL,
    [DELETED_BY] INT NULL,

    CONSTRAINT [PK_PRODUCTO_COMPRA] PRIMARY KEY CLUSTERED ([COMPRA_ID] ASC, [PROD_ID] ASC)
) ON [PRIMARY];
GO

CREATE NONCLUSTERED INDEX [IX_PRDCOM_PROD]
ON [dbo].[PRODUCTO_COMPRA]([PROD_ID] ASC);
GO

ALTER TABLE [dbo].[PRODUCTO_COMPRA] WITH CHECK
ADD CONSTRAINT [CK_PRDCOM_CANT] CHECK ([PRDCOM_CANTIDAD] > (0));
GO

ALTER TABLE [dbo].[PRODUCTO_COMPRA] WITH CHECK
ADD CONSTRAINT [CK_PRDCOM_PREC] CHECK ([PRDCOM_PRECIO] >= (0));
GO

/* =========================================
   9) Foreign Keys negocio BD_TRANSACCIONES
   ========================================= */
ALTER TABLE [dbo].[FACTURA] WITH CHECK
ADD CONSTRAINT [FK_FACTURA_CLIENTE]
FOREIGN KEY ([CLI_ID]) REFERENCES [dbo].[CLIENTE]([CLI_ID]);
GO

ALTER TABLE [dbo].[FACTURA] WITH CHECK
ADD CONSTRAINT [FK_FACTURA_TIPO_PAGO]
FOREIGN KEY ([TPA_ID]) REFERENCES [dbo].[TIPO_PAGO]([TPA_ID]);
GO

ALTER TABLE [dbo].[PRODUCTO_FACTURA] WITH CHECK
ADD CONSTRAINT [FK_PF_FACTURA]
FOREIGN KEY ([FAC_ID]) REFERENCES [dbo].[FACTURA]([FAC_ID]);
GO

ALTER TABLE [dbo].[COMPRA] WITH CHECK
ADD CONSTRAINT [FK_COMPRA_PROVEEDOR]
FOREIGN KEY ([PROV_ID]) REFERENCES [dbo].[PROVEEDOR]([PROV_ID]);
GO

ALTER TABLE [dbo].[PRODUCTO_COMPRA] WITH CHECK
ADD CONSTRAINT [FK_PRDCOM_COMPRA]
FOREIGN KEY ([COMPRA_ID]) REFERENCES [dbo].[COMPRA]([COMPRA_ID]);
GO

/* =========================================
   10) Nota de integridad referencial lógica
   =========================================
   NO se crean estas FKs porque viven en otra BD:
   - FACTURA.USU_ID -> BD_CATALOGO.dbo.USUARIO(USU_ID)
   - COMPRA.USU_ID -> BD_CATALOGO.dbo.USUARIO(USU_ID)
   - KARDEX.USU_ID -> BD_CATALOGO.dbo.USUARIO(USU_ID)
   - PRODUCTO_FACTURA.PROD_ID -> BD_CATALOGO.dbo.PRODUCTO(PROD_ID)
   - PRODUCTO_COMPRA.PROD_ID -> BD_CATALOGO.dbo.PRODUCTO(PROD_ID)
   - KARDEX.PROD_ID -> BD_CATALOGO.dbo.PRODUCTO(PROD_ID)
   - CREATED_BY / UPDATED_BY / DELETED_BY -> BD_CATALOGO.dbo.USUARIO(USU_ID)
   ========================================= */
GO
